blank_issues_enabled: true
contact_links:
  - name: Using issue-helper to create issue
    url: https://akinocccc.github.io/material-v3/issue-helper/?lang=en-US&repo=akinocccc/material-v3
    about: Using https://Tencent.github.io/material-v3/issue-helper/ to create issue.