name: Feature report
description: Suggest an idea for this project.
title: "A title for the feature"
labels: ["feature report"]
body:

- type: textarea
  id: problemDescription
  label: Is your feature request related to a problem? Please describe
  description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
  placeholder: Please input

- type: textarea
  id: solutionDescription
  label: Describe the solution you'd like
  descrition: A clear and concise description of what you want to happen.
  placeholder: Please input

- type: textarea
  id: alternation
  label: Describe alternatives you've considered
  descrition: A clear and concise description of any alternative solutions or features you've considered.
  placeholder: Please input

- type: textarea
  id: addition
  label:Additional context
  descrition: Add any other context or screenshots about the feature request here.
  placeholder: Please input
