name: Auto-Assign

on:
  push:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - uses: akinocccc/select-collaborators@1.1.1
        id: candidate
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: |
          echo "candidates: ${{ steps.candidate.outputs['candidates'] }}"
          - run: |
              echo "candidates: ${{ steps.candidate.outputs['candidates_string'] }}"
      - run: |
          echo "collaborators: ${{ steps.candidate.outputs['collaborators'] }}"

      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # using the `org/team_slug` or `/team_slug` syntax to add git team as reviewers
          reviewers: ${{ steps.candidate.outputs['candidates_string'] }}
          assignees: ${{ steps.candidate.outputs['candidates_string'] }}
          skipKeywords: wip, draft

      - name: 通知贡献者
        if: steps.candidate.outputs.at_candidates_string != ''
        uses: actions-cool/maintain-one-comment@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ♥️ 有劳 ${{ steps.candidate.outputs.at_candidates_string }} 尽快确认问题。
            确认有效后将下一步计划和可能需要的时间回复给 @${{ github.event.issue.user.login }} 。
            <!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->
          number: ${{ github.event.issue.number }}
          body-include: '<!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->'
