name: Auto-Assign

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: Get contributors
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.github.com/repos/akinocccc/test/contributors
          method: GET
          headers: |
            Accept: application/vnd.github.v3+json
          auth: |
            username: ${{ github.actor }}
            password: ${{ secrets.GH_TOKEN }}
        id: assignees

      - run: echo ${{ steps.assignees.outputs.data }}
      - name: Add assigness
        if: steps.assignees.outputs.data != ''
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: ${{ steps.assignees.outputs.data }}

      - run: |
          contributors=${{ steps.assignees.outputs.data }}
          contributorstring=${contributors//,/ @}
          echo "::set-output name=string::@$contributorstring"
        id: contributors

      - name: 通知贡献者
        if: steps.assignees.outputs.contributors != ''
        uses: actions-cool/maintain-one-comment@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ♥️ 有劳 ${{ steps.contributors.outputs.string }} 尽快确认问题。
            确认有效后将下一步计划和可能需要的时间回复给 @${{ github.event.issue.user.login }} 。
            <!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->
          number: ${{ github.event.issue.number }}
          body-include: "<!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->"