name: Add Assigness

on:
  issues:
    types: [opened, edited]

jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - uses: 94dreamer/issue-assignees@main
        id: assignees
        with:
          project_name: ${{github.event.repository.name}}
          issue_title: ${{github.event.issue.title}}

      - run: echo ${{ steps.assignees.outputs.contributors }}
      - name: Add assigness
        if: steps.assignees.outputs.contributors != ''
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: ${{ steps.assignees.outputs.contributors }}

      - run: |
          contributors=${{ steps.assignees.outputs.contributors }}
          contributorstring=${contributors//,/ @}
          echo "::set-output name=string::@$contributorstring"
        id: contributors

      - name: Notification
        if: steps.assignees.outputs.contributors != ''
        uses: actions-cool/maintain-one-comment@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ♥️ Please ${{ steps.contributors.outputs.string }} to confirm the issue as soon as possible. After confirmation, please reply to @${{ github.event.issue.user.login }} with the next step plan and the estimated time needed.
            <!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->
          number: ${{ github.event.issue.number }}
          body-include: "<!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->"