name: Add Assigness

on:
  issues:
    types: [opened, edited]

jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: Get Collaborators
        id: collaborators
        uses: actions/github-script@v4
        with:
          script: |
            const { data: repoData } = await github.repos.get({ owner: context.repo.owner, repo: context.repo.repo });
            core.info(`Collaborators: ${JSON.stringify(repoData)}`);
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        

      - name: Add assigness
        if: steps.collaborators.outputs.data.collaborators != ''
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: ${{ steps.assignees.outputs.collaborators }}

      - run: |
          collaborators=${{ steps.assignees.outputs.collaborators }}
          collaboratorstring=${collaborators//,/ @}
          echo "::set-output name=string::@$collaboratorstring"
        id: template

      - name: Notification
        if: steps.assignees.outputs.collaborators != ''
        uses: actions-cool/maintain-one-comment@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ♥️ Please ${{ steps.template.outputs.string }} to confirm the issue as soon as possible. After confirmation, please reply to @${{ github.event.issue.user.login }} with the next step plan and the estimated time needed.
            <!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->
          number: ${{ github.event.issue.number }}
          body-include: "<!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->"