name: Issue Add Assigness

on:
  issues:
    types: [opened, edited]

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}, Thanks for submitting your issue. We'll look into it and keep you updated on our progress. Let us know if you have any questions.

      # https://docs.github.com/cn/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issues
      - uses: 94dreamer/issue-assignees@main
        id: assignees
        with:
          project_name: ${{github.event.repository.name}}
          issue_title: ${{github.event.issue.title}}

      - run: echo ${{ steps.assignees.outputs.contributors }}
      - name: Add assigness
        if: steps.assignees.outputs.contributors != ''
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: ${{ steps.assignees.outputs.contributors }}

      - run: |
          contributors=${{ steps.assignees.outputs.contributors }}
          contributorstring=${contributors//,/ @}
          echo "::set-output name=string::@$contributorstring"
        id: contributors

      - name: Notification
        if: steps.assignees.outputs.contributors != ''
        uses: actions-cool/maintain-one-comment@v2.0.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          body: |
            ♥️ Please ${{ steps.contributors.outputs.string }} confirm the issue and reply the plan or other infomation to @${{ github.event.issue.user.login }}.
            <!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->
          number: ${{ github.event.issue.number }}
          body-include: "<!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->"