name: Release
on: 
  push: 
    branches:
      - master
jobs:
  release:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: lts/Hydrogen

      - name: Install
        run: yarn && npm audit fix

      - name: Pubilsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: materialgithubbot@gmail.com
          GIT_AUTHOR_NAME: release-bot
          GIT_COMMITTER_EMAIL: materialgithubbot@gmail.com
          GIT_COMMITTER_NAME: release-bot
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release